[package]
name = "roguelike"
version = "0.1.0"
authors = ["panicbit <panicbit.dev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rltk = "0.7.0"
specs = "0.16.1"
specs-derive = "0.4.1"
